### ISSUE TITLE
Support for grails 3.0.3

### ISSUE THREAD

**Issue by sanketmaru** [balsamiq/jsx-grails-asset-pipeline#3]
Is the support for grails 3.0.3 supported ?
I want the jsx transformer and es6 to es5 to work with grails 3.0.3

**Comment by kaaloo** [comment]
Hi, I'm sorry no it's not likely that we will be moving to grails 3 just yet.  I haven't tried it myself but maybe the babel asset pipeline plugin will help?

https://github.com/peh/grails-babel-asset-pipeline

This plugin also needs some love to work with the latest grails asset pipeline plugin 2.X series. Thanks for getting in touch though!
